name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_habits: yes
          plugin_reactions: yes
          plugin_lines: yes
          plugin_stargazers: yes
          plugin_projects: yes
          plugin_activity: yes
          plugin_achievements: yes
          plugin_notable: yes
          plugin_skyline: yes
