name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_habits: yes
          plugin_lines: yes
          plugin_activity: yes
          plugin_notable: yes
          plugin_achievements: yes
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_provider: spotify
          plugin_music_user: ${{ secrets.SPOTIFY_USERNAME }}
          plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
          plugin_gists: yes
          plugin_reactions: yes
          plugin_people: yes
          plugin_people_types: followers, following, sponsors, stargazers
          plugin_topics: yes
